#!/usr/bin/env bash

# folder navigation
alias ~='cd ~'
alias -- -='cd -'
alias ...=../..
alias ....=../../..
alias .....=../../../..
alias ......=../../../../..

alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls -G'
alias lsa='ls -lah'
alias md='mkdir -p'
alias rd=rmdir
alias _='sudo '

alias afind='ack -il'
alias history=omz_history
alias run-help=man
alias which-command=whence

# fasd
alias a='fasd -a'
alias d='fasd -d'
alias f='fasd -f'
alias j=zz
alias op='a -e open'
alias s='fasd -si'
alias sd='fasd -sid'
alias sf='fasd -sif'
alias v='f -e "$EDITOR"'
alias z='fasd_cd -d'
alias zz='fasd_cd -d -i'

# http://www.zzapper.co.uk/zshtips.html
#-------- Global Alias {{{
#------------------------------------------------------
# Automatically Expanding Global Aliases (Space key to expand)
# references: http://blog.patshead.com/2012/11/automatically-expaning-zsh-global-aliases---simplified.html 
globalias() {
  if [[ $LBUFFER =~ '[A-Z0-9]+$' ]]; then
    zle _expand_alias
    zle expand-word
  fi
  zle self-insert
}
zle -N globalias
bindkey " " globalias                 # space key to expand globalalias
# bindkey "^ " magic-space            # control-space to bypass completion
bindkey "^[[Z" magic-space            # shift-tab to bypass completion
bindkey -M isearch " " magic-space    # normal space during searches

alias C='| wc -l'
alias CA='2>&1 | cat -A'
alias G='| grep'
alias H='| head'
alias L='| less'
alias LL='2>&1 | less'
alias M='| most'
alias ND='*(/om[1])'
alias NE='2> /dev/null'
alias NF='*(.om[1])'
alias NO='&>|/dev/null'
alias NUL='> /dev/null 2>&1'
alias P='2>&1 | $PAGER'
alias T='| tail'
alias VV='| vim -R -'
