#!/usr/bin/env bash

# Make vim the default editor.
export EDITOR='vim'

# Make less the default pager.
export PAGER='less'

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8'

# Console colors
export LSCOLORS="Gxfxcxdxbxegedabagacad"

# Secrets
[[ ! -f ~/.secret ]] || source ~/.secret
