#!/usr/bin/env bash

set -e

OS_RELEASE="/etc/os-release"
DOCKERENV="/.dockerenv"

[[ ! -f ${OS_RELEASE} ]] || eval "DISTRO_$(cat ${OS_RELEASE} | grep '^ID=')"

if [[ -f ${DOCKERENV} ]]; then
  if [[ ${DISTRO_ID} -eq "alpine" ]]; then
    apk update
    apk add shadow python3 perl openssh ncurses zsh 
  fi
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
